version: '2'
volumes:
 postgres_data:
     driver: local
     
services:
  gateway:
    image: thetlwinoo/vertical-gateway
    container_name: vertical-gateway
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vertical_gateway'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://auth.rangoon-tech.com/auth/realms/jhipster'
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.entrypoints=http"
      - "traefik.http.routers.gateway.rule=Host(`system.zezawar.com`)"
      - "traefik.http.middlewares.gateway-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vertical.middlewares=gateway-https-redirect"
      - "traefik.http.routers.gateway-secure.entrypoints=https"
      - "traefik.http.routers.gateway-secure.rule=Host(`system.zezawar.com`)"
      - "traefik.http.routers.gateway-secure.tls=true"
      # - "traefik.http.routers.gateway-secure.tls.certresolver=http"
      - "traefik.http.routers.gateway-secure.service=gateway"
      - "traefik.http.services.gateway.loadbalancer.server.port=8180"
      - "traefik.docker.network=proxy"
    ports:
      - 8180:8180  

  vertical_commerce:
    image: thetlwinoo/vertical-commerce
    container_name: vertical-commerce
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/zezawar_db'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://auth.rangoon-tech.com/auth/realms/jhipster'
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30
      # - 'SPRING_DATA_JEST_URI=http://zezawar-elasticsearch:9200'
      # - 'SPRING_ELASTICSEARCH_REST_URIS=http://zezawar-elasticsearch:9200'
    labels:
      - "traefik.enable=false"
    ports:
      - 8181:8181

  vertical_cloudblob:
    image: thetlwinoo/vertical-cloudblob
    container_name: vertical-cloudblob
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATA_MONGODB_URI=mongodb://cloudblob-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=cloudblob
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://auth.rangoon-tech.com/auth/realms/jhipster'
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30
    labels:
      - "traefik.enable=false"
    ports:
      - 8182:8182

    # zezawar-elasticsearch:
    #   image: 'docker.elastic.co/elasticsearch/elasticsearch:6.8.6'
    #   container_name: zezawar-elasticsearch
    #   environment:
    #     - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    #     - discovery.type=single-node
    #   ports:
    #     - 9200:9200
    #     - 9300:9300

  # vsgateway:
  #   extends:
  #     file: vertical-gateway.yml
  #     service: vsgateway 
  # vscommerce:
  #   extends:
  #     file: vertical-commerce.yml
  #     service: vscommerce
  # vscloudblob:
  #   extends:
  #     file: vertical-cloudblob.yml
  #     service: vscloudblob
  consul:
    extends:
      file: consul.yml
      service: consul
  consul-config-loader:
    extends:
      file: consul.yml
      service: consul-config-loader  
  vertical-portal:
    extends:
      file: vertical-portal.yml
      service: vsportal
  vertical-seller:
    extends:
      file: vertical-seller.yml
      service: vsseller 
  vertical-online:
    extends:
      file: vertical-online.yml
      service: vsonline 
  traefik:
    extends:
      file: traefik.yml
      service: reverse-proxy
  portainer:
    extends:
      file: portainer.yml
      service: portainer
  postgres:
    extends:
      file: keycloak.yml
      service: postgres
  keycloak:
    extends:
      file: keycloak.yml
      service: keycloak
  cloudblob-mongodb:
    extends:
      file: mongodb.yml
      service: cloudblob-mongodb  

networks:
  proxy:
    external: true