version: '2'

services:
  sellerapp:
    image: thetlwinoo/eps-seller:test
    # container_name: vertical-gateway
    container_name: eps-seller
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://auth.rangoon-tech.com/auth/realms/jhipster'
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sellerapp.entrypoints=http"
      - "traefik.http.routers.sellerapp.rule=Host(`seller.zezawar.com`)"
      - "traefik.http.middlewares.sellerapp-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.sellerapp.middlewares=sellerapp-https-redirect"
      - "traefik.http.routers.sellerapp-secure.entrypoints=https"
      - "traefik.http.routers.sellerapp-secure.rule=Host(`seller.zezawar.com`)"
      - "traefik.http.routers.sellerapp-secure.tls=true"
      # - "traefik.http.routers.seller-secure.tls.certresolver=http"
      - "traefik.http.routers.sellerapp-secure.service=sellerapp"
      - "traefik.http.services.sellerapp.loadbalancer.server.port=81"
      - "traefik.docker.network=proxy"
    ports:
      - 8082:81
    depends_on:
      - vertical
networks:
  proxy:
    external: true