version: '2'
volumes:
 postgres_data:
     driver: local

services:
  vsgateway:
    image: thetlwinoo/vertical-gateway
    container_name: vertical-gateway
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vertical_gateway
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/auth/realms/jhipster'
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vsgateway.entrypoints=http"
      - "traefik.http.routers.vsgateway.rule=Host(`system.zezawar.com`)"
      - "traefik.http.middlewares.vsgateway-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vertical.middlewares=vsgateway-https-redirect"
      - "traefik.http.routers.vsgateway-secure.entrypoints=https"
      - "traefik.http.routers.vsgateway-secure.rule=Host(`system.zezawar.com`)"
      - "traefik.http.routers.vsgateway-secure.tls=true"
      # - "traefik.http.routers.vsgateway-secure.tls.certresolver=http"
      - "traefik.http.routers.vsgateway-secure.service=vsgateway"
      - "traefik.http.services.vsgateway.loadbalancer.server.port=8180"
      - "traefik.docker.network=proxy"
    ports:
      - 8180:8180
# networks:
#   proxy:
#     external: true