version: '2'

services:
  vsonline:
    image: thetlwinoo/vertical-online
    container_name: vertical-online
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://auth.rangoon-tech.com/auth/realms/jhipster'
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vsonline.entrypoints=http"
      - "traefik.http.routers.vsonline.rule=Host(`www.zezawar.com`)"
      - "traefik.http.middlewares.vsonline-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vsonline.middlewares=vsonline-https-redirect"
      - "traefik.http.routers.vsonline-secure.entrypoints=https"
      - "traefik.http.routers.vsonline-secure.rule=Host(`www.zezawar.com`)"
      - "traefik.http.routers.vsonline-secure.tls=true"
      # - "traefik.http.routers.seller-secure.tls.certresolver=http"
      - "traefik.http.routers.vsonline-secure.service=vsonline"
      - "traefik.http.services.vsonline.loadbalancer.server.port=82"
      - "traefik.docker.network=proxy"
    ports:
      - 8083:82
    # depends_on:
    #   - vertical
networks:
  proxy:
    external: true