version: '2'

services:
  vertical:
    image: thetlwinoo/epm-web:v6.5.1
    container_name: vertical-monolithic
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/vertical'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://auth.rangoon-tech.com/auth/realms/jhipster'
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vertical.entrypoints=http"
      - "traefik.http.routers.vertical.rule=Host(`system.zezawar.com`)"
      - "traefik.http.middlewares.vertical-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vertical.middlewares=vertical-https-redirect"
      - "traefik.http.routers.vertical-secure.entrypoints=https"
      - "traefik.http.routers.vertical-secure.rule=Host(`system.zezawar.com`)"
      - "traefik.http.routers.vertical-secure.tls=true"
      # - "traefik.http.routers.vertical-secure.tls.certresolver=http"
      - "traefik.http.routers.vertical-secure.service=vertical"
      - "traefik.http.services.vertical.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    ports:
      - 8080:8080
    depends_on:
      - keycloak
networks:
  proxy:
    external: true