version: '2'

services:
  vsportal:
    image: thetlwinoo/vertical-portal
    container_name: vertical-portal
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://auth.rangoon-tech.com/auth/realms/jhipster'
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=internal
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=internal
      - JHIPSTER_SLEEP=30
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vsportal.entrypoints=http"
      - "traefik.http.routers.vsportal.rule=Host(`portal.zezawar.com`)"
      - "traefik.http.middlewares.vsportal-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.vsportal.middlewares=vsportal-https-redirect"
      - "traefik.http.routers.vsportal-secure.entrypoints=https"
      - "traefik.http.routers.vsportal-secure.rule=Host(`portal.zezawar.com`)"
      - "traefik.http.routers.vsportal-secure.tls=true"
      # - "traefik.http.routers.vertical-secure.tls.certresolver=http"
      - "traefik.http.routers.vsportal-secure.service=vsportal"
      - "traefik.http.services.vsportal.loadbalancer.server.port=81"
      - "traefik.docker.network=proxy"
    ports:
      - 8081:81
    # depends_on:
    #   - keycloak
networks:
  proxy:
    external: true