version: '2'

services:
  epmtest:
    image: thetlwinoo/epm-test:v1
    # container_name: vertical-gateway
    container_name: vertical-test
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      proxy:
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - 'SPRING_PROFILES_ACTIVE=prod,swagger'
      # - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      # - SPRING_CLOUD_CONSUL_HOST=consul
      # - SPRING_CLOUD_CONSUL_PORT=8500
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/testing'
      - 'SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=https://auth.rangoon-tech.com/auth/realms/jhipster'
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - JHIPSTER_SLEEP=30
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.epmtest.entrypoints=http"
      - "traefik.http.routers.epmtest.rule=Host(`test.zezawar.com`)"
      - "traefik.http.middlewares.epmtest-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.epmtest.middlewares=epmtest-https-redirect"
      - "traefik.http.routers.epmtest-secure.entrypoints=https"
      - "traefik.http.routers.epmtest-secure.rule=Host(`test.zezawar.com`)"
      - "traefik.http.routers.epmtest-secure.tls=true"
      # - "traefik.http.routers.vertical-secure.tls.certresolver=http"
      - "traefik.http.routers.epmtest-secure.service=epmtest"
      - "traefik.http.services.epmtest.loadbalancer.server.port=8081"
      - "traefik.docker.network=proxy"
    ports:
      - 8081:8081
    depends_on:
      - keycloak
networks:
  proxy:
    external: true