providers:
  consulCatalog:
    prefix: traefik
    exposedByDefault: false
    defaultRule: "PathPrefix(`/services/{{.ServiceName}}`)"
    endpoint:
      address: "consul:8500"
      scheme: https
api:
  dashboard: true
  insecure: true
  debug: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

# log:
#   level: DEBUG
#   filePath: /path/to/log-file.log
#   format: json

# tracing:
#   servicename: tracing
#   jaeger:
#     samplingParam: 1
#     samplingServerURL: 'http://12.0.0.1:5778/sampling'
#     samplingType: const
#     localAgentHostPort: '12.0.0.1:6831'

# metrics:
#   prometheus:
#     buckets:
#       - 0.1
#       - 0.3
#       - 1.2
#       - 5
#     entryPoint: metrics

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml

certificatesResolvers:
  cloudflare:
    acme:
      email: rangoon-tech@outlook.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"